Add wasm support for both web and node envrionment
Phala-Network/dcap-qvl pull request #1
Opened 2024-10-11 03:25 UTC by tolak

This is PR is going to adding wasm support for both web and node envrionment by compile the library to `wasm-unknow-unknown` target.
Note that `js` feature should be enabled and due to tls not been supportted by WASM, `get_collateral` will be disabled at the time

2024-10-15 14:54 UTC, kvinwang requested changes

2024-10-15 14:54 UTC, kvinwang commented on Cargo.toml
> +serde_bytes = "0.11"
Let's make them optional and enbable them by the feature `js`.

2024-10-15 14:54 UTC, kvinwang commented on src/verify.rs
> +#[wasm_bindgen]
```suggestion
#[cfg(feature = "js")]
#[wasm_bindgen]
```

2024-10-15 15:07 UTC, kvinwang commented
> Note that `js` feature should be enabled and due to tls not been supportted by WASM, `get_collateral` will be disabled at the time

AFAIK, the reqwest supports running in browser. Is there any problem to export the `get_collateral` as well?

2024-10-17 03:24 UTC, kvinwang approved these changes
Great work. Thanks a lot.

2024-10-17 03:32 UTC, 0xshawn commented
Here are the changes to reviewed comments:
- Make wasm related denpendencies optional and add them to js feature
- Fix errors reported by `cargo check`

2024-10-17 03:33 UTC, merged